"""mongo ref id

Revision ID: a3c8a837c782
Revises: 7a8048517a17
Create Date: 2026-10-05 13:43:05.819514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3c8a837c782'
down_revision: Union[str, Sequence[str], None] = '7a8048517a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('mongo_ref_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'mongo_ref_id')
    # ### end Alembic commands ###
